using System.Collections.Generic;
using ExpandedLib.BlockMigrations;
using Vintagestory.API.Common;
using Vintagestory.API.Server;

namespace PipesAndPowerExpanded.BlockMigrations;

/// <summary>
/// Migrates the pipe network and steam-power machines that moved out of Steelmaking Expanded
/// (<c>smex</c>) into this mod (<c>ppex</c>). Pipes were also renamed <c>gaspipe-* → pipe-*</c>;
/// the boiler, Cornish engine, fluid pump and MP generator keep their path and only change
/// domain. The air/gas blower stays in <c>smex</c> and is deliberately not remapped.
///
/// <para>The remap is generated by walking the registered <c>ppex</c> blocks and pairing each
/// with its old <c>smex</c> code, so it always matches the current variant set. A handful of
/// pre-brick legacy passthrough/outlet codes (which a very old save still carries) are mapped
/// straight to the refractory-tier3 variant so those migrate in one hop too.</para>
/// </summary>
public class PipeMigration : IBlockCodeMigration
{
  public string Name => "Pipes and steam power moved to ppex";

  public IEnumerable<(AssetLocation oldCode, AssetLocation newCode)> GetRemaps(
    ICoreServerAPI api
  )
  {
    // Direct moves: every current ppex pipe / engine / boiler block ← its old smex code.
    foreach (Block block in api.World.Blocks)
    {
      if (block?.Code == null || block.Code.Domain != "ppex")
        continue;

      string path = block.Code.Path;
      string? oldPath = path switch
      {
        _ when path.StartsWith("pipe-") => "gas" + path, // pipe-... → gaspipe-...
        _ when path.StartsWith("fluidintake") => path,
        _ when path.StartsWith("cornishengine") => path,
        _ when path.StartsWith("cornishfluidpump") => path,
        _ when path.StartsWith("cornishmpgenerator") => path,
        _ when path.StartsWith("boilerlancashire") => path,
        _ when path.StartsWith("boiler-steamoutlet") => path,
        _ => null,
      };
      if (oldPath == null)
        continue;

      yield return (new AssetLocation("smex", oldPath), block.Code.Clone());
    }

    // Pre-brick legacy passthrough/outlet (before the refractory-tier variantgroup existed).
    string[] passOrients = ["ns", "we", "ud"];
    foreach (string o in passOrients)
      yield return (
        new AssetLocation("smex", $"gaspipe-passthrough-{o}"),
        new AssetLocation("ppex", $"pipe-passthrough-refractorytier3-{o}")
      );

    string[] outletOrients = ["s", "n", "w", "e"];
    foreach (string o in outletOrients)
      yield return (
        new AssetLocation("smex", $"gaspipe-outlet-{o}"),
        new AssetLocation("ppex", $"pipe-outlet-refractorytier3-{o}")
      );
  }
}
